// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/banner': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/banner').default>>>>
    }
    '/api/image': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image').default>>>>
    }
    '/api/img': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/img.get').default>>>>
    }
    '/api/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/list').default>>>>
    }
    '/api/qiniu-file': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qiniu-file').default>>>>
    }
    '/api/qiniu-link': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qiniu-link').default>>>>
    }
    '/api/qiniu-preview': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qiniu-preview').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@unocss+reset@0.58.6_async-validator@4_4hniqsuiy64r7hq2xdqx2ihbpi/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_mdc/highlight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+mdc@0.6.1_rollup@3.29.4/node_modules/@nuxtjs/mdc/dist/runtime/highlighter/event-handler').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.3.2_nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@un_n24hl7hihjezsfnsjdsdc4jba4/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.3.2_nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@un_n24hl7hihjezsfnsjdsdc4jba4/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.3.2_nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@un_n24hl7hihjezsfnsjdsdc4jba4/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.3.2_nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@un_n24hl7hihjezsfnsjdsdc4jba4/node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.3.2_nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@un_n24hl7hihjezsfnsjdsdc4jba4/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.3.2_nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@un_n24hl7hihjezsfnsjdsdc4jba4/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@2.12.1_ioredis@5.3.2_nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@18.19.26_@un_n24hl7hihjezsfnsjdsdc4jba4/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
  }
}
export {}